services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./salon_booking
    volumes:
      - ./salon_booking:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    command: >
      sh -c "echo 'Waiting for database...' &&
             while ! nc -z db 3306; do sleep 1; done &&
             echo 'Database is up!' &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./salon-booking-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
